### ISSUE TITLE
Bug: Multiple ships of the same type are not supported

### ISSUE THREAD

**Issue by evertvorster** [vegastrike/Vega-Strike-Engine-Source#867] opened 2024-06-21 09:07 UTC
Hi there!

The game engine allows you to buy multiple ships of the same type, however it does not really support it. 
It would appear that the ship is saved in a file with just the type as the file name. When you buy a second ship of the same type, that ship just disappears, as it is using the same file to write the information to. 

Now the next question is why would you want to have multiple ships of the same type?
In my use case, I am running cargo between a factory base and a arid planet. It is quite profitable, and the only ship that is available in the region that has a biggish cargo space is the Plowshare. They are fairly cheap and plentiful, and so it would only be natural to have the desire to have multiple Plowshares to handle especially large cargo assignments. 

In any case, the game engine should check to see if there is already a ship of the same type that is being purchased, and if so, add a number to the file name to indicate the number of the ship in the series of ship that you own. It would also be useful to have this information displayed in your fleet info. 

So, let's say you are flying a Dovtesky and three Plowshares. 
The first Plowshare would show up as Plowshare, the second as Plowshare_1, the next one Plowshare_2 and so on. 

These names should also be persistent, even if you sell the middle one in the series, so the game engine should be smart enough to read all your ships even if one in the middle of a series is missing. 

One thought would be a sort of conflict checking and subsequent naming scheme for ships in your fleet.

**Comment by royfalk** [comment] 2024-09-08 06:39
Duplicate of #757. Closing.

**Closed by royfalk** 2024-09-08 06:39 UTC
Labels: bug
