### ISSUE TITLE
Bug program hangs during execution -first mission

### ISSUE THREAD

**Issue by LifWirser** [vegastrike/Vega-Strike-Engine-Source#23] opened 2020-02-24 23:38 UTC

**Comment by LifWirser** [comment] 2020-02-24 23:40
Occurred on Intel core2 (64 bit) , Debian 9, mesa graphics from Vega-Strike-Engine-Source-0.5.3.zip
During first execution(s) of VS, during first flight, game hangs up hard!
- on linux use {cntrl}{alt}{F1}(for Debian 9, other linux's may vary) to escape xwindows , then login again at prompt and issue this command

Code: Select all
    killall -9 vegastrike


Then issue {cntrl}{alt}{F7} (for Debian 9, other linux's may vary) to return to xwindows.
After this Vegastrike has not yet observed to hang on subsiquent executions.
This appears to be a problem with Python compiling a module during first time running. possibly waiting long enough will solve problem - no errors were observed on shell terminal.

**Comment by LifWirser** [comment] 2020-02-26 23:08
THIS IS STILL NEEDING MORE TESTING, I have repeatible results but need to verify
 cpuopts not the issue (doubtfull)

In tracking this bug I found by chance that compiling with cpu opts changed to "core 2"
 and boost set to internal I don.t get locked up on first mission. In order to compile,
your os packages are needed for boost-dev(boost development), along with packages that
 provide:<Python.h>,<boost/python.hpp>,<boost/python/class.hpp>,<boost/python/object.hpp>

in top vegastrike diredtory
edit ./engine/CMakeLists.txt
search for "Use system boost"
change option from "OFF" to "ON"
save file
rm -rf build ( just to be sure )
exicute  sh/vsbuild.sh 

for the more cautious, All saved games and all options set via ./bin/vssetup will be lost.
run  "find . -name *.pyc | xargs /bin/rm -f" ( I doubt this is needed but it doesn't hurt"
and "rm -rf ~/.vegastrike" ( again may not be needed, but just to be sure)

run vegastrike as normal

**Comment by LifWirser** [comment] 2020-02-27 22:06
Note: boost version provided in  /ext is 1.72 my internal boost for Debian 9 is 1.62. Will update as new informaion available

**Comment by nabaco** [comment] 2020-04-28 21:31
Hi @LifWirser, is this bug still reproducible?
Other developers and I haven't seen the issue on the latest code, and some of them are running on Debian too.
Could you please supply logs from running the game. The logs can be collected with the following command:

`./vegastrike > output.log 2 > error.log`

Then post the two files here so we'll be able to further analyze them.

**Comment by BenjamenMeyer** [comment] 2021-06-07 23:17
Current release for Linux is 0.7.0, and we've had quite a few changes since 0.5.3 - enough that we're not supporting 0.5.x on Linux any more. Windows will be joining the updated round too soon too. Mac will be the only platform remaining on 0.5.x for the time being as we haven't had time to fix the builds there yet (no devs on Mac right now).

Closing for now. @LifWirser if you can reproduce using current master then please re-open and update the bug information.

**Closed by BenjamenMeyer** 2021-06-07 23:17 UTC
Labels: bug
