### ISSUE TITLE
BUG base database appears to be corrupt

### ISSUE THREAD

**Issue by LifWirser** [vegastrike/Vega-Strike-Engine-Source#24] opened 2020-02-24 23:46 UTC
Occurred on Intel core2 (64 bit) , Debian 9, mesa graphics from Vega-Strike-Engine-Source-0.5.3.zip

-It appears the database is corrupt, in more than one system: missions are listed as "scan" or "visit" with no apparent location, clues are that all are "real" meaning can be found by cycling "n", using placement in mission list provides usefull clues. All have no names: one miningbase in enyo system, another miningbase in pandey(sp), and in everest a location with no descrition which seems not to be either a base or jumppoint but shows up as a valid taget

**Comment by nabaco** [comment] 2020-04-28 21:56
This sounds like an issue with the Assets.
@LifWirser could you please supply a screenshot so we'll have a better understanding of the issue, and game logs with the following command?
`./vegastrike > output.log 2 > error.log`

**Comment by BenjamenMeyer** [comment] 2020-04-28 22:31
@LifWirser what asset set are you using?

**Comment by BenjamenMeyer** [comment] 2021-06-07 23:18
Current release for Linux is 0.7.0, and we've had quite a few changes since 0.5.3 - enough that we're not supporting 0.5.x on Linux any more. Windows will be joining the updated round too soon too. Mac will be the only platform remaining on 0.5.x for the time being as we haven't had time to fix the builds there yet (no devs on Mac right now).

Closing for now. @LifWirser if you can reproduce using current master then please re-open and update the bug information.

**Closed by BenjamenMeyer** 2021-06-07 23:18 UTC
Labels: bug
