### ISSUE TITLE
Unit file contraband not found - Python 2

### ISSUE THREAD

**Issue by evertvorster** [vegastrike/Vega-Strike-Engine-Source#151] opened 2020-06-23 10:10 UTC
Hi there!

I am play-testing VegaStrike, and looking for low-hanging fruit to be fixed. 
The game and assets are both from the latest git. 

When the game starts up with the Python 2 and related boost libs, I get a lot of "Unit file contraband not found"

This _should_ be a low hanging fruit, as that file has to be somewhere. It's not in current Assets or Engine. There are a few contraband files in the various factions in Assets, and it's mentioned in the 
units_description.csv file.

It may solve bigger problems, or it may just provide some polish, but as it stands now, when you launch Vega Strike from the command line, you get this sort of output:

[evert@Vorster vegastrike]$ vegastrike --debug
Registering codec ogg.
 In path /usr/bin
Vega Strike  
See http://www.gnu.org/copyleft/gpl.html for license details.

ARG #1 = --debug
GOT SUBDIR ARG = 
Found data in /usr/share/vegastrike
Using /usr/share/vegastrike as data directory
Using .vegastrike as the home directory
Found MODDIR = /usr/share/vegastrike/mods
USING HOMEDIR : /home/evert/.vegastrike As the home directory 
CONFIGFILE - Found a config file in home directory, using : /home/evert/.vegastrike/vegastrike.config
DATADIR - No datadir specified in config file, using ; /usr/share/vegastrike
SIMULATION_ATOM: 0.01
MISSION_NAME is empty using : main_menu.mission
running import sys
print(sys.path)
sys.path = ["",r"/usr/share/vegastrike/modules/builtin",r"/usr/share/vegastrike/modules/quests",r"/usr/share/vegastrike/modules/missions",r"/usr/share/vegastrike/modules/ai",r"/usr/share/vegastrike/modules",r"/usr/share/vegastrike/bases"] + sys.path
['/usr/lib/python27.zip', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-linux2', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload']
testing VS randomrunning import sys
print(sys.path)
['', '/usr/share/vegastrike/modules/builtin', '/usr/share/vegastrike/modules/quests', '/usr/share/vegastrike/modules/missions', '/usr/share/vegastrike/modules/ai', '/usr/share/vegastrike/modules', '/usr/share/vegastrike/bases', '/usr/lib/python27.zip', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-linux2', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload']
Creating scene manager...
Creating template manager...
  Initializing renderer...
Fragment info
\-------------
0(142) : warning C7050: "mtl_gloss" might be used before being initialized

1 joysticks were found.

The names of the joysticks are:
    Logitech Logitech Freedom 2.4
axes: 4 buttons: 10 hats: 1
FactionXML:LoadXML factions.xml
using NV_CUBE_MAP
Min (0.000000, 0.000000, 0.000000) Max(0.000000, 0.000000, 0.000000) MinLumin 1.000000, MaxLumin 1.000000Read In Star Count 0 used: 2000
Min (0.000000, 0.000000, 0.000000) Max(0.000000, 0.000000, 0.000000) MinLumin 1.000000, MaxLumin 1.000000Read In Star Count 0 used: 38
Loading a starsystem
Loading Star System Special/Empty
FOUND MODIFICATION = player FOR PLAYER #0
CREATING A LOCAL SHIP : dumbfire
Hi helper play 0
HereInitializing optimizer
Compilation of technique fixed successful
Fragment info
\-------------
0(197) : warning C7050: "mtl_gloss" might be used before being initialized

Compilation of technique default successful
Compilation of technique default_simple successful
pox 119990000000.000000 -9000000.000000 -109990000000.000000
CreateVideoTexture could not find preintro.ogv
INFO: Missing video stream preintro.ogv
CreateVideoTexture could not find intro.ogv
INFO: Missing video stream intro.ogv
Force feedback support disabled when compiled
Unit file contraband not found
Unit file contraband not found
Unit file contraband not found
Unit file contraband not found
Unit file contraband not found
Unit file contraband not found
Unit file contraband not found
Unit file contraband not found
Unit file contraband not found
Unit file contraband not found
Unit file contraband not found
Unit file contraband not found
Unit file contraband not found
Unit file contraband not found
Unit file contraband not found
Unit file contraband not found
Unit file contraband not found
Unit file contraband not found
Unit file contraband not found
Unit file contraband not found
Unit file contraband not found
Unit file contraband not found
Unit file contraband not found
Unit file contraband not found
Unit file contraband not found
Unit file contraband not found
Unit file contraband not found
Unit file contraband not found
Unit file contraband not found
Unit file contraband not found
Unit file contraband not found
Unit file contraband not found
Unit file contraband not found
Unit file contraband not found
Unit file contraband not found
Unit file contraband not found
Unit file contraband not found
Unit file contraband not found
Unit file contraband not found
Loading active missions True
('', ' IS NOW AT ', 'Special/Empty')

Launching bases for Special/Empty
Adding news
Shutting down renderer...
Thank you for playing!
Writing Save Game Autosave-main_menu
Hi helper play 0
UNIT DELETION QUEUED: LOAD_FAILED contraband (file contraband, addr 0x059ea470)
Deallocating unit LOAD_FAILED addr=0x059ea470 refs=0
UNIT DELETION QUEUED: LOAD_FAILED contraband (file contraband, addr 0x059e8c30)
Deallocating unit LOAD_FAILED addr=0x059e8c30 refs=0
UNIT DELETION QUEUED: LOAD_FAILED contraband (file contraband, addr 0x059eb000)
Deallocating unit LOAD_FAILED addr=0x059eb000 refs=0
UNIT DELETION QUEUED: LOAD_FAILED contraband (file contraband, addr 0x05293dc0)
Deallocating unit LOAD_FAILED addr=0x05293dc0 refs=0
UNIT DELETION QUEUED: LOAD_FAILED contraband (file contraband, addr 0x052942f0)
Deallocating unit LOAD_FAILED addr=0x052942f0 refs=0
UNIT DELETION QUEUED: LOAD_FAILED contraband (file contraband, addr 0x05294820)
Deallocating unit LOAD_FAILED addr=0x05294820 refs=0
UNIT DELETION QUEUED: LOAD_FAILED contraband (file contraband, addr 0x056a1af0)
Deallocating unit LOAD_FAILED addr=0x056a1af0 refs=0
UNIT DELETION QUEUED: LOAD_FAILED contraband (file contraband, addr 0x056a2020)
Deallocating unit LOAD_FAILED addr=0x056a2020 refs=0
UNIT DELETION QUEUED: LOAD_FAILED contraband (file contraband, addr 0x056a2790)
Deallocating unit LOAD_FAILED addr=0x056a2790 refs=0
UNIT DELETION QUEUED: LOAD_FAILED contraband (file contraband, addr 0x059d3e30)
Deallocating unit LOAD_FAILED addr=0x059d3e30 refs=0
UNIT DELETION QUEUED: LOAD_FAILED contraband (file contraband, addr 0x059d45d0)
Deallocating unit LOAD_FAILED addr=0x059d45d0 refs=0
UNIT DELETION QUEUED: LOAD_FAILED contraband (file contraband, addr 0x056c1780)
Deallocating unit LOAD_FAILED addr=0x056c1780 refs=0
UNIT DELETION QUEUED: LOAD_FAILED contraband (file contraband, addr 0x056c1f40)
Deallocating unit LOAD_FAILED addr=0x056c1f40 refs=0
UNIT DELETION QUEUED: LOAD_FAILED contraband (file contraband, addr 0x056a4790)
Deallocating unit LOAD_FAILED addr=0x056a4790 refs=0
UNIT DELETION QUEUED: LOAD_FAILED contraband (file contraband, addr 0x056a4cc0)
Deallocating unit LOAD_FAILED addr=0x056a4cc0 refs=0
UNIT DELETION QUEUED: LOAD_FAILED contraband (file contraband, addr 0x056a54b0)
Deallocating unit LOAD_FAILED addr=0x056a54b0 refs=0
UNIT DELETION QUEUED: LOAD_FAILED contraband (file contraband, addr 0x05251510)
Deallocating unit LOAD_FAILED addr=0x05251510 refs=0
UNIT DELETION QUEUED: LOAD_FAILED contraband (file contraband, addr 0x05251a40)
Deallocating unit LOAD_FAILED addr=0x05251a40 refs=0
UNIT DELETION QUEUED: LOAD_FAILED contraband (file contraband, addr 0x052523e0)
Deallocating unit LOAD_FAILED addr=0x052523e0 refs=0
UNIT DELETION QUEUED: LOAD_FAILED contraband (file contraband, addr 0x05252d80)
Deallocating unit LOAD_FAILED addr=0x05252d80 refs=0
UNIT DELETION QUEUED: LOAD_FAILED contraband (file contraband, addr 0x056c7fd0)
Deallocating unit LOAD_FAILED addr=0x056c7fd0 refs=0
UNIT DELETION QUEUED: LOAD_FAILED contraband (file contraband, addr 0x056c8a20)
Deallocating unit LOAD_FAILED addr=0x056c8a20 refs=0
UNIT DELETION QUEUED: LOAD_FAILED contraband (file contraband, addr 0x056c9470)
Deallocating unit LOAD_FAILED addr=0x056c9470 refs=0
UNIT DELETION QUEUED: LOAD_FAILED contraband (file contraband, addr 0x056c5e10)
Deallocating unit LOAD_FAILED addr=0x056c5e10 refs=0
UNIT DELETION QUEUED: LOAD_FAILED contraband (file contraband, addr 0x056c67b0)
Deallocating unit LOAD_FAILED addr=0x056c67b0 refs=0
UNIT DELETION QUEUED: LOAD_FAILED contraband (file contraband, addr 0x056c7150)
Deallocating unit LOAD_FAILED addr=0x056c7150 refs=0
UNIT DELETION QUEUED: LOAD_FAILED contraband (file contraband, addr 0x056a6340)
Deallocating unit LOAD_FAILED addr=0x056a6340 refs=0
UNIT DELETION QUEUED: LOAD_FAILED contraband (file contraband, addr 0x056a6d60)
Deallocating unit LOAD_FAILED addr=0x056a6d60 refs=0
UNIT DELETION QUEUED: LOAD_FAILED contraband (file contraband, addr 0x056a77b0)
Deallocating unit LOAD_FAILED addr=0x056a77b0 refs=0
UNIT DELETION QUEUED: LOAD_FAILED contraband (file contraband, addr 0x056a8200)
Deallocating unit LOAD_FAILED addr=0x056a8200 refs=0
UNIT DELETION QUEUED: LOAD_FAILED contraband (file contraband, addr 0x056a8c80)
Deallocating unit LOAD_FAILED addr=0x056a8c80 refs=0
UNIT DELETION QUEUED: LOAD_FAILED contraband (file contraband, addr 0x056a96d0)
Deallocating unit LOAD_FAILED addr=0x056a96d0 refs=0
UNIT DELETION QUEUED: LOAD_FAILED contraband (file contraband, addr 0x056aa120)
Deallocating unit LOAD_FAILED addr=0x056aa120 refs=0
UNIT DELETION QUEUED: LOAD_FAILED contraband (file contraband, addr 0x056aab70)
Deallocating unit LOAD_FAILED addr=0x056aab70 refs=0
UNIT DELETION QUEUED: LOAD_FAILED contraband (file contraband, addr 0x056ab5c0)
Deallocating unit LOAD_FAILED addr=0x056ab5c0 refs=0
UNIT DELETION QUEUED: LOAD_FAILED contraband (file contraband, addr 0x056ac010)
Deallocating unit LOAD_FAILED addr=0x056ac010 refs=0
UNIT DELETION QUEUED: LOAD_FAILED contraband (file contraband, addr 0x056aca60)
Deallocating unit LOAD_FAILED addr=0x056aca60 refs=0
UNIT DELETION QUEUED: LOAD_FAILED contraband (file contraband, addr 0x056ad4b0)
Deallocating unit LOAD_FAILED addr=0x056ad4b0 refs=0
UNIT DELETION QUEUED: LOAD_FAILED contraband (file contraband, addr 0x059d67a0)
Deallocating unit LOAD_FAILED addr=0x059d67a0 refs=0
Here[evert@Vorster vegastrike]$

**Comment by BenjamenMeyer** [comment] 2020-06-23 13:01
@evertvorster can you confirm if this is active in 0.6.x? Sounds like something we should fix for that release if we can.

**Comment by evertvorster** [comment] 2020-06-23 15:05
@BenjamenMeyer, I can confirm that this exact issue is in the 0.6.x branch, as well as the stable branch. 
I suspect that this is an issue of the Assets rather than the engine, as it is looking for a file or variable that does not exist. 
This may not be such a serious issue, as the game runs with it. As I mentioned in the initial report, it does detract from the initial impression of the game, and appears to be pretty low-hanging fruit.

**Comment by evertvorster** [comment] 2020-06-23 15:24
Oh, man. Just reverted my local copy of the Assets-Production git back to the last commit from 2014. It still has this same issue.

**Comment by BenjamenMeyer** [comment] 2020-06-23 16:10
@evertvorster cool - let's try to find a fix for 0.6.x.

Let's confirm this is an issue with the Asset Data, and if so then we'll transfer this issue to the Asset Masters repo.

**Comment by evertvorster** [comment] 2020-06-23 16:38
@BenjamenMeyer 
When I run the Wing Commander Privateer with the Vega Strike engine, I do not get this error message....  I really have to hack at it a little harder to see what is causing the message. Hopefully it's something small.

**Comment by evertvorster** [comment] 2020-06-23 16:46
@BenjamenMeyer, more basically, can we rule out whether it's my packaging of Vega Strike? Do you get the same error messages when you start up Vega Strike?

**Comment by BenjamenMeyer** [comment] 2020-06-23 17:26
@evertvorster I'll try to confirm tonight EDT.

**Comment by BenjamenMeyer** [comment] 2020-06-24 02:47
@evertvorster I can confirm I'm seeing it too. The message isn't terribly useful though as it doesn't tell what file it can't actually find. Not sure if that's an Asset-side issue or an Engine side issue....I'll leave it here until we can fix that part and assume it's engine side for the moment - that is, the error message itself. Once we've fixed that we can then determine if anything further is asset or engine side.

I'm going to guess there's a reference to `contraband` that isn't quite right on the asset side, but without the fixed error message it'll be very hard to find.

**Comment by evertvorster** [comment] 2020-06-24 05:46
@BenjamenMeyer Hmm, I know correlation is not causation.... but there are 39 instances of "contraband" not found, and 39 instances of "contraband" in the factions.xml file from Assets-Production

Now I just have to figure out the purpose and function of factions.xml

**Comment by BenjamenMeyer** [comment] 2020-06-25 04:49
@evertvorster yes, I can change the error message by changing one of those lines, so there is certainly a relationship. The big problem is that I don't know what the XML format should be.

@Loki1950 @pyramid3d we need some information on how to convert Asset Masters to Asset Productions and the design of the XML that gets loaded. 

Background:

I found in the Engine code some of the info around the faction data, and where the error is generated in https://github.com/vegastrike/Vega-Strike-Engine-Source/blob/master/engine/src/cmd/unit_generic.cpp#L1264; however, I can't figure out what VS thinks the current directory is, and the load command seems to be trying to load it from the current directory. Any tips?

NOTE: I found `current_directory` which is a vector of strings, but it seems to be empty; and `current_path.back()+current_directory.back()+current_subdirectory.back()` (from vsfilesystem) also produces an empty value.

**Comment by evertvorster** [comment] 2020-06-25 09:20
@BenjamenMeyer There is some documentation tangenically related to this here:
https://wiki.vega-strike.org/HowTo:Add_Upgrades
https://wiki.vega-strike.org/HowTo:Add_Descriptions

Both of those links to the wiki looks like it was aimed at the Privateer Gemini Gold remake. When we figure out all the knobs and how to make things work, we'll have to update the Wiki as well.

**Comment by BenjamenMeyer** [comment] 2020-06-25 13:16
@evertvorster unfortunately those are for ship mods; I can't find anything in the Wiki regarding contraband and the XML data.

**Comment by BenjamenMeyer** [comment] 2020-06-26 14:07
Like with #153 the game works; if we can find a solution sooner than later great, but I'm going to move this to the same milestone as it's not blocking game play.

**Comment by BenjamenMeyer** [comment] 2020-07-28 04:17
@evertvorster  is this still happening with the unit.csv merge?

**Comment by pyramid3d** [comment] 2020-08-02 14:59
I think contraband is a cargo unit. As such, this may also be related to https://wiki.vega-strike.org/HowTo:Add_Cargo, where the contraband entry might be missing from master_parts_list.csv.
It may also be that there is no sprite entry for contraband in the units.csv file and the engine is complaining about that.
But not sure though what is the real cause.

**Comment by BenjamenMeyer** [comment] 2021-06-08 00:12
@evertvorster @pyramid3d is this still an issue? Or can we close it out?

**Comment by evertvorster** [comment] 2021-06-08 21:19
From my side this can be closed...

Evert Vorster
Awesome Chapters Tours
http://www.awesomechapters.com
Tel: +264 (0) 811477690

**Closed** 2021-06-09 02:22 UTC
Labels: bug
