### ISSUE TITLE
Multi-monitor...

### ISSUE THREAD

**Issue by BenjamenMeyer** [vegastrike/Vega-Strike-Engine-Source#36] opened 2020-04-04 18:51 UTC
I typically use my laptop hooked up to a second display; when loading vegastrike. I build VS and then used the Asset Production set to play the VS screen takes over both monitors and centers itself between them instead of sticking to one screen or the other.

1. Is this expected behavior? (I'm thinking not)
2. What data can I provide to help resolve?
3. What can I do to help out on this? It makes game play a bit interesting and hard; though it does seem to work.

OS: Linux - Kubuntu 19.04

**Comment by BenjamenMeyer** [comment] 2020-04-07 04:45
Here's a screen shot of game play.
Some things to note:
1. The screen below is not quite centered across two monitors; the unused space doesn't show up in the screen shot but appears grey on the screen. The monitor break goes through the image about one quarter the way into the right radar HUD.
2. The data in the lower right portion isn't visible - the bottom of the actual screen area that is visible is near the top of the nav computer display showing the planet; the Right Side Radar HUD is partially visible, but only what shows up on my left hand monitor; anything that should be on the right hand monitor isn't visible.

![Screenshot4](https://user-images.githubusercontent.com/1074110/78630552-0724b700-7868-11ea-8eae-0fb8090f13e0.png)

Note: This is on a laptop with an attached external monitor with both set to the same resolution, but differing actual physical sizes.

My expectation is that Vegastrike choose a single monitor device and only use that one device; even if the other is blank. Having it split between two monitors is rather hard to see what is going on.

**Comment by royfalk** [comment] 2020-04-07 05:15
I’m not sure if it’s worth pursuing at this point.
Some of these problems may go away if we move to Ogre and this one doesn’t sound easy to solve well.
My vote is to document and put on hold until we can figure out the ogre schedule.

**Comment by BenjamenMeyer** [comment] 2020-04-07 13:38
@royfalk that's fine. I think it's just a matter of adding settings to control the viewport; I might investigate from that angle as in my normal setup it's very hard to play, especially missing part of the screen.

At least for the moment, it's not a high priority - we need to get things moving as a community first.

**Comment by Loki1950** [comment] 2020-04-07 17:34
IIRC assigning monitor settings is handled by SDL and it changed from SDL1 and SDL2 my normal work station has two monitors

**Comment by BenjamenMeyer** [comment] 2020-04-17 03:38
Work around right now is to just use Windowed mode instead of Full Screen mode.
I think that's generally acceptable until we can get proper multi-monitor support in.

**Comment by Loki1950** [comment] 2020-04-17 16:58
When in testing mode I use to run in widowed mode from a terminal window for max info

**Comment by BenjamenMeyer** [comment] 2020-04-19 03:00
@Loki1950 probably one of those things we need to document for testing purposes.

**Comment by nabaco** [comment] 2020-04-28 21:38
Hi @BenjamenMeyer, for further triage, we might need the following information:

1. System specs (OS, graphics card and driver, xrandr output)
2. VS configuration (./vssetup screenshot might be enough)
3. Game log (`./vegastrike > output.log 2 > error.log`)

Out of curiosity, how is your laptop hooked up? Directly or through a docking station?

**Comment by BenjamenMeyer** [comment] 2020-04-28 22:27
@nabaco yes; we should outline how to collect that information and provide it.

System Specs:
- HP ProBook 4530s (2012?)
- Kubuntu 19.10
- Xrandr:
```
Screen 0: minimum 320 x 200, current 3286 x 1080, maximum 8192 x 8192
LVDS-1 connected 1366x768+1920+0 (normal left inverted right x axis y axis) 344mm x 194mm
   1366x768      60.03*+
   1360x768      59.80    59.96  
   1280x720      60.00    59.99    59.86    59.74  
   1024x768      60.04    60.00  
   960x720       60.00  
   928x696       60.05  
   896x672       60.01  
   1024x576      59.95    59.96    59.90    59.82  
   960x600       59.93    60.00  
   960x540       59.96    59.99    59.63    59.82  
   800x600       60.00    60.32    56.25  
   840x525       60.01    59.88  
   864x486       59.92    59.57  
   800x512       60.17  
   700x525       59.98  
   800x450       59.95    59.82  
   640x512       60.02  
   720x450       59.89  
   700x450       59.96    59.88  
   640x480       60.00    59.94  
   720x405       59.51    58.99  
   684x384       59.88    59.85  
   680x384       59.80    59.96  
   640x400       59.88    59.98  
   576x432       60.06  
   640x360       59.86    59.83    59.84    59.32  
   512x384       60.00  
   512x288       60.00    59.92  
   480x270       59.63    59.82  
   400x300       60.32    56.34  
   432x243       59.92    59.57  
   320x240       60.05  
   360x202       59.51    59.13  
   320x180       59.84    59.32  
VGA-1 disconnected (normal left inverted right x axis y axis)
HDMI-1 connected primary 1920x1080+0+0 (normal left inverted right x axis y axis) 527mm x 296mm
   1920x1080     60.00*+  50.00    59.94  
   1920x1080i    60.00    50.00    59.94  
   1600x900      60.00  
   1280x1024     75.02    60.02  
   1152x864      75.00  
   1280x720      60.00    50.00    59.94  
   1024x768      75.03    60.00  
   800x600       75.00    60.32  
   720x576       50.00  
   720x576i      50.00  
   720x480       60.00    59.94  
   720x480i      60.00    59.94  
   640x480       75.00    60.00    59.94  
   720x400       70.08  
DP-1 disconnected (normal left inverted right x axis y axis)
```
- 
[vegastrike.config.txt](https://github.com/vegastrike/Vega-Strike-Engine-Source/files/4548879/vegastrike.config.txt)
![xorg-config](https://user-images.githubusercontent.com/1074110/80543670-6c5a5c80-897d-11ea-96b4-436714fa4510.png)

I'll have to capture the rest later.
As to how it's hooked up - this laptop doesn't have a docking station (would love to have one though); so the monitor is just plugged in as an external monitor via the HDMI port. KDE is configured such that the display is extended to the other monitor - thus the disparity between the xranderr output (noting the settings of the individual displays) and the Xorg Config image (noting how Xorg sees the displays). I expect SDL will see what Xorg tells it is there, and the difference in physical sizes might also be causing some of the disparity too since VegaStrike is trying to treat the whole area as one big display mat and it's not really - the two displays are actually two different sizes.

**Comment by nabaco** [comment] 2020-04-28 22:39
When I'll get to the wiki I'll write up a page on that too. Maybe I'll setup a Github template for Bug issues.

Can you try and run the game with this resolution `1280x800`? Or with a resolution that has the same aspect ratio? This is only as an experiment, since I saw some difference in the configuration file accross different resolutions.

**Comment by evertvorster** [comment] 2024-06-11 13:50
This is definitely something to be addressed when we get to polishing the game engine. 

Settings should be part of the game engine, and not be a separate binary. 
As mentioned earlier in this bug, this would be addressed when fixing the rendering engine.

This specific issue is unfortunately the first thing that a person who is newly interested in Vega-Strike would be seeing, and conceivably this is a turn-off.

**Comment by royfalk** [comment] 2024-11-25 19:42
This should have been solved by #876 .

**Comment by evertvorster** [comment] 2024-11-26 05:18
#876 Did indeed solve the issue, for a bit. 
However, now this setting in vegastrike.config seems to be ignored by the engine in master. 
If this setting moved to config.json, what are the steps to specify the monitor to start up on in config.json?

**Comment by royfalk** [comment] 2024-11-26 12:22
The settings moved as is to config.json. 

```
"graphics": {
    "resolution_x": 2560,
    "resolution_y": 1600,
    "screen": 0 <<<
}
```

The old vegasettings app never supported it, so this isn't a regression. If you want to specify the monitor, you have to edit the file.

**Comment by evertvorster** [comment] 2024-11-26 12:29
Thanks for the explanation! 
It works on my machine now. I have to specify "2" as a screen number to work. 

Thanks again. Closing the ticket.

**Closed by evertvorster** 2024-11-26 12:29 UTC
Labels: bug
