### ISSUE TITLE
Loss of Yaw controls

### ISSUE THREAD

**Issue by BenjamenMeyer** [vegastrike/Vega-Strike-Engine-Source#793] opened 2023-08-14 02:03 UTC
I have often run into an issue when taking off - or having a reload where it starts off-planet - where I do not have any Yaw control. To overcome this I have to then roll and pitch to be able to make manual turns. I've observed it can often get reset by landing and taking off again - but it goes both ways.

NOTE: This is only the controls. It does not effect the autopilot from changes courses.

Image compliments of Wikipedia (https://en.wikipedia.org/wiki/Aircraft_principal_axes)
![image](https://github.com/vegastrike/Vega-Strike-Engine-Source/assets/1074110/e80132d8-90f8-46a9-96df-e26f2a987ecd)

Note: I'm filing this against all current supported and future releases, but I don't expect we'll likely fix it until at least 0.10.x. If we are able to figure it out and fix it for 0.9.x that'd be great but not expecting it.

**Comment by Loki1950** [comment] 2023-08-15 00:16
@BenjamenMeyer @DMJC posted this on gitter https://en.wikipedia.org/wiki/Gimbal_lock there's a math solution at the end of the article

**Comment by BenjamenMeyer** [comment] 2023-08-15 01:44
I think it loses input recognition for yaw from mouse and keyboard.

**Comment by stephengtuggy** [comment] 2023-12-05 05:54
I am also experiencing this issue. Turning with the joystick doesn't work either. But auto-ejecting allows me to turn again, in my pilot escape pod.

Very odd. I would say this should be a high priority to get fixed. It represents a loss of essential game functionality.

**Comment by BenjamenMeyer** [comment] 2023-12-06 14:30
This might be related to #823 which is looking at this from the saved game loading perspective

**Comment by evertvorster** [comment] 2024-06-11 17:14
I have noticed this as well when loading a save file that has been modified. In my case the save file was on Atlantis, but after modifying some Accel parameters in the ship's serialized xml file, the save game loads in space, undocked from Atlantis.
I am playing with mouse glide, rather that joystick. If this is simply gimbal lock, you should be able to maneuver out of it by turning 90 degrees. 

Also, if it was gimbal lock, autopilot should not be able to turn either. This may be something completely different.

**Comment by evertvorster** [comment] 2024-06-11 17:54
Another funny thing I noticed with the modified save game is that the SPEC drive did not activate. All the indications on the screen were that it was active, but the speed multiplier stayed stuck at 1 while flying away from Atlantis. This persisted until 5000km away from Atlantis where I ran out of patience and exited the game.

**Comment by evertvorster** [comment] 2024-06-15 12:46
Hi there!
I run into this when I load a saved game. 
In the .vegastrike/serialized_xml directory there is a directory that matches the save game name. 
In that directory is a list of ships that I currently own. 
When looking at the csv file for the ship, I can see that the Yaw_Governor_Left and Yaw_Governor_Right is 0, where it should be matching the Yaw_Governor in the previous column, at least on an undamaged ship. 

I don't know what is causing this, but it definitely points to a problem with the generation of that file when the game is saved. Unfortunately, when I put those values back to normal, I still have no Yaw controls when I load the saved game.

**Comment by stephengtuggy** [comment] 2024-06-21 02:02
@evertvorster Yeah, I don't think it's a case of gimbal lock. Happens much too frequently for that. I think the cause is something else.

**Comment by evertvorster** [comment] 2024-06-21 06:22
Jip, I got to the bottom of the error, it is documented in #865

**Comment by BenjamenMeyer** [comment] 2024-08-13 05:27
@evertvorster nice

**Comment by royfalk** [comment] 2024-09-08 06:36
Dup of #865, which properly diagnoses this. Closing.

**Closed by royfalk** 2024-09-08 06:36 UTC
Labels: bug
